//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class display_appointements_for_Patient
    {
        public int TimeSlotId { get; set; }
        public int PatientId { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public string Doctor { get; set; }
        public Nullable<bool> Is_Available { get; set; }
    }
}
